# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testPractice1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'Toast', '~> 4.0.0'
pod 'AFNetworking'

  # Pods for testPractice1

end
